language: php

php:
  - 5.3
  - 5.4
  - 5.5

env:
  matrix:
    - SYMFONY_VERSION=2.3.*
    - SYMFONY_VERSION=2.6.*

before_script:
  - composer require --prefer-source --dev symfony/symfony:${SYMFONY_VERSION}
  - cp phpunit.xml.dist phpunit.xml

script:
  - phpunit

services:
  - redis-server
